# -*- coding: utf-8 -*-
"""person

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/183-DJLaK6Zn1W-TvNmzbu8-KnISBxdyM
"""

# Programming Task Part C: Creating person.py

class person:
    name = " "
    age = 0
    height = 0
    
    def __init__(self, name, age, height):
        self.name = name  
        self.age = age
        self.height = height

# Programming Task Part D: Creating __repr__(self)
    def __repr__(self):
        repr = "{:} is {:} years old and {:} cm tall.".format(self.name, self.age, self.height)
        return repr


new_person = person(name='Joe',age=34,height=184)
print("{:} is {:} years old.".format(new_person.name, new_person.age))
print(repr(new_person))
bob = person(name='Bob', age=17, height=182)
print(repr(bob))

